#pragma once

#include "MoveComponent.hpp"
#include "Math.hpp"

// follows a sequence of points generated by pathfinding
class NavComponent : public MoveComponent {
public:
	// lower update order to update first
	NavComponent(class Actor* owner, int updateOrder = 10);

	void Update(float deltaTime) override;
	void StartPath(const class Tile* start);

	// rotate the actor to face a point
	void TurnTo(const Vector2& pos);

private:
	const class Tile* mNextNode;  // tracks the next point in the path
};